<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5559" started-at="2018-05-30T08:06:00Z" finished-at="2018-05-30T08:06:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5559" started-at="2018-05-30T08:06:00Z" finished-at="2018-05-30T08:06:06Z">
      <class name="homePage.VerifyHomePage">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:homePage.VerifyHomePage@26be92ad]" name="beforeMethod" is-config="true" duration-ms="2232" started-at="2018-05-30T09:06:00Z" finished-at="2018-05-30T09:06:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="testVerifyHomePage()[pri:0, instance:homePage.VerifyHomePage@26be92ad]" name="testVerifyHomePage" duration-ms="1009" started-at="2018-05-30T09:06:03Z" finished-at="2018-05-30T09:06:04Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Product table is not available on the page expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Product table is not available on the page expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at homePage.VerifyHomePage.testVerifyHomePage(VerifyHomePage.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testVerifyHomePage -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:homePage.VerifyHomePage@26be92ad]" name="afterMethod" is-config="true" duration-ms="2308" started-at="2018-05-30T09:06:04Z" finished-at="2018-05-30T09:06:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- homePage.VerifyHomePage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
